### ISSUE TITLE
Integrate relevant part of `cbir_tfe`

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-cbir#13]
# Description

The requirement of [cbir-tfe](https://github.com/AxelleSchyns/cbir-tfe) contains many unrelevant packages for the current state of cbir.

# Task

- [x] Integrate relevant part of `cbir_tfe`:
    - [x] The Resnet model
    - [x] The dataset
    - [x] The database
- [x] Remove the dependency to `cbir_tfe`.
- [x] Add the minimum required dependency to run the models
